config/routes.rb
Hadean::Application.routes.draw do

  get "contacts/index"

  resources :user_sessions, :only => [:new, :create, :destroy]

  match 'admin'   => 'admin/overviews#index'
  match 'login'   => 'user_sessions#new'
  match 'logout'  => 'user_sessions#destroy'
  match 'signup'  => 'customer/registrations#new'
  match 'admin/merchandise' => 'admin/merchandise/summary#index'

  get 'about', to: 'statics#about'
  get 'privacy', to: 'statics#privacy'
  get 'terms', to: 'statics#terms'
  get 'contact', to: 'statics#contact'
  post 'send_inquiry', to: 'statics#send_inquiry'

  match 'browse' => 'products#index', as: 'browse'
  match 'category/:product_type_id' => 'products#index', as: 'browse_category'
  match 'color/:property_values_id' => 'products#index', as: 'browse_color'
  match 'price/:price_from' => 'products#index', as: 'browse_price_from'
  match 'price/:price_from/:price_to' => 'products#index', as: 'browse_price_from_to'
  match 'search' => 'products#index', as: 'search'
  match 'search/:search_term' => 'products#index', as: 'search_term'
  
  match 'hallists/search' => 'hallists#index', as: 'hallists_search'
  match 'hallists/search/:search_term' => 'hallists#index', as: 'hallists_search_term'
  
  match 'artists/search' => 'artists#index', as: 'artists_search'
  match 'artists/search/:search_term' => 'artists#index', as: 'artists_search_term'

  match 'contacts/newsletter' => 'contacts#newsletter', as: 'newsletter'
  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'

  match 'collections/delete_collection/:id' => 'collections#delete_collection', as: 'delete_collection'

  resources :comments
  resources :bids, only: [:create]
  
  resources :products, :only => [:index, :show, :create] do
    resources :collection_cart_items, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy], controller: 'products/likes'
  end

  resources :artists, only: [:index] do
    resource :follows, only: [:create, :destroy]
  end

  resources :collections,  :only => [:destroy, :create, :update, :show]
  resources :hallists,  :only => [:index, :destroy, :create, :update, :show]
  resources :states,      :only => [:index]
  resource :about,        :only => [:show]

  root :to => "products#index"

  namespace :customer do
    resources :registrations,   :only => [:new, :create]
    resource  :password_reset,  :only => [:new, :create, :edit, :update]
    resource  :activation,      :only => [:show]
  end

  namespace :myaccount do
    resources :orders, :only => [:index, :show]
    resources :addresses
    resources :credit_cards
    resource  :store_credit, :only => [:show]
    resource  :overview, :only => [:show, :edit, :update]
  end

  namespace :artwork do
    resource :dashboard, only: :show, controller: 'dashboard'
    resources :products do
      resources :variants, only: :destroy
    end
  end

  namespace :shopping do
    resource :paypal_checkout, controller: :paypal_checkout do
      member do
        get :review
      end
    end

    resource :creditcard_checkout, controller: :creditcard_checkout do
      member do
        post :pay
      end
    end

    resources  :cart_items do
      member do
        put :move_to
      end
    end
    resource  :coupon, :only => [:show, :create]
    resources  :orders do
      member do
        get :checkout
      end
    end
    resource :checkout, controller: :checkout, only: [:show, :update] do
      member do
        post :twocheckout_return
      end
    end
    resources  :shipping_methods
    resources  :addresses do
      member do
        put :select_address
      end
    end

  end

  namespace :admin do
    resources :users
    resources :overviews, :only => [:index]

    match "help" => "help#index"

    namespace :rma do
      resources  :orders do
        resources  :return_authorizations do
          member do
            put :complete
          end
        end
      end
      #resources  :shipments
    end

    namespace :history do
      resources  :orders, :only => [:index, :show] do
        resources  :addresses, :only => [:index, :show, :edit, :update, :new, :create]
      end
    end

    namespace :fulfillment do
      resources  :orders do
        member do
          put :create_shipment
        end
        resources  :comments
      end
      resources  :shipments do
        member do
          put :ship
        end
        resources  :addresses , :only => [:edit, :update]# This is for editing the shipment address
      end
    end
    namespace :shopping do
      resources :carts
      resources :products
      resources :users
      namespace :checkout do
        resources :billing_addresses, :only => [:index, :update, :new, :create, :select_address] do
          member do
            put :select_address
          end
        end
        resources :credit_cards
        resource  :order, :only => [:show, :update, :start_checkout_process] do
          member do
            post :start_checkout_process
          end
        end
        resources :shipping_addresses, :only => [:index, :update, :new, :create, :select_address] do
          member do
            put :select_address
          end
        end
        resources :shipping_methods, :only => [:index, :update]
      end
    end
    namespace :config do
      resources :accounts
      resources :overviews
      resources :shipping_categories
      resources :shipping_rates
      resources :shipping_methods
      resources :shipping_zones
      resources :tax_rates
      resources :tax_categories
      resources :messages
    end

    namespace :generic do
      resources :coupons
      resources :deals
    end
    namespace :inventory do
      resources :suppliers
      resources :overviews
      resources :purchase_orders
      resources :receivings
      resources :adjustments
    end

    namespace :merchandise do
      namespace :images do
        resources :products
      end
      resources :properties
      resources :prototypes
      resources :brands
      resources :product_types
      resources :prototype_properties

      namespace :changes do
        resources :products do
          resource :property,          :only => [:edit, :update]
        end
      end

      namespace :wizards do
        resources :brands,              :only => [:index, :create, :update]
        resources :products,            :only => [:new, :create]
        resources :properties,          :only => [:index, :create, :update]
        resources :prototypes,          :only => [:update]
        resources :tax_categories,        :only => [:index, :create, :update]
        resources :shipping_categories, :only => [:index, :create, :update]
        resources :product_types,       :only => [:index, :create, :update]
      end

      namespace :multi do
        resources :products do
          resource :variant,      :only => [:edit, :update]
        end
      end
      resources :products do
        member do
          get :add_properties
          put :activate
          get :featured
        end
        resources :variants
      end
      namespace :products do
        resources :descriptions, :only => [:edit, :update]
      end
    end
    namespace :document do
      resources :invoices
    end
  end

  match '/subregion_options', to: 'application#subregion_options'
  match '/artworks/:id', :to => 'products#show', :as => 'artwork'

  match '/myprofile', :to => 'profile#show', :as => 'myprofile'
  match '/profile/:profile_id/products', :to => 'profiles/products#index', :as => 'profile_products'
  match '/profile/:profile_id/collections', :to => 'profiles/collections#index', :as => 'profile_collections'
  match '/profile/:id', :to => 'profile#show', :as => 'profile'
  match '/:username', :to => 'profile#show', :as => 'personal_urls'
  post '/webhooks/receptor'
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :buy_quantity, :deal_type_id, :get_percentage, :product_type_id, :get_amount

  validates :buy_quantity,            :presence => true
  validates :get_percentage,          :presence => true, :if => :get_amount_is_blank?
  validates :product_type_id,         :presence => true
  validates :get_amount,              :presence => true, :if => :get_percentage_is_blank?

  belongs_to :deal_type
  belongs_to :product_type

  def self.best_qualifing_deal(order)
    product_type_and_amount_hash = order.number_of_a_given_product_type.sort_by{|v| v.last.size }.reverse
    deal_time = order.completed_at || Time.zone.now # Deal.best_qualifing_deal(ooo)
    product_type_and_amount_hash.each do |h|
      deal_amount = qualifing_deal(h, deal_time)
      return deal_amount.round_at(2) if deal_amount
    end
    0.0
  end
  def self.qualifing_deal(h, at)
    deal = self.where(['deals.buy_quantity <= ?', h.last.size]).
    where(['deals.product_type_id IN (?)', h.first]).
    where(['deals.created_at <= ?', at]).where(['deals.deleted_at >= ? OR deals.deleted_at IS NULL', at]).
    order('deals.get_percentage DESC').first
    if deal && deal.get_amount && deal.get_amount > 0.0
      deal.get_amount.to_f / 100.0
    else
      deal ?  ((h.last.sort.reverse[0..(deal.buy_quantity - 1)].min) * deal.get_percentage).to_f / 100.0 : false
    end
  end

  # [item1.price,item2.price,item3.price ].sort.reverse[0..4].min

  private
    def get_percentage_is_blank?
      get_percentage.blank?
    end
    def get_amount_is_blank?
      get_amount.blank?
    end
end

app/models/deal_type.rb
class DealType < ActiveRecord::Base
  attr_accessible :name

  validates :name,            :presence => true

  has_many :deals
  TYPES = ['Buy X Get % off', 'Buy X Get $ off']
end

app/controllers/admin/generic/base_controller.rb
class Admin::Generic::BaseController < Admin::BaseController

end

app/controllers/admin/generic/coupons_controller.rb
class Admin::Generic::CouponsController < Admin::Generic::BaseController
  def index
    @coupons = Coupon.all
  end

  def show
    @coupon = Coupon.find(params[:id])
  end

  def new
    form_info
    @coupon = Coupon.new
  end

  def create
      if params[:coupon][:c_type] == 'coupon_value'
        @coupon = CouponValue.new(params[:coupon])
      elsif params[:coupon][:c_type] == 'coupon_percent'
        @coupon = CouponPercent.new(params[:coupon])
      else
        @coupon = Coupon.new(params[:coupon])
        @coupon.errors.add(:base, 'please select coupon type')
      end
    if @coupon.errors.size == 0 && @coupon.save
      flash[:notice] = "Successfully created coupon."
      redirect_to admin_generic_coupon_url(@coupon)
    else
      form_info
      render :action => 'new'
    end
  end

  def edit
    form_info
    @coupon = Coupon.find(params[:id])
  end

  def update
      @coupon = Coupon.find(params[:id])
    if @coupon.update_attributes(params[:coupon])
      flash[:notice] = "Successfully updated coupon."
      redirect_to admin_generic_coupon_url(@coupon)
    else
      form_info
      render :action => 'edit'
    end
  end

  def destroy
    @coupon = Coupon.find(params[:id])
    @coupon.destroy
    flash[:notice] = "Successfully destroyed coupon."
    redirect_to admin_generic_coupons_url
  end

  private

  def form_info
    @coupon_types = Coupon::COUPON_TYPES
  end
end

app/controllers/admin/generic/deals_controller.rb
class Admin::Generic::DealsController < Admin::Generic::BaseController
  helper_method :sort_column, :sort_direction, :product_types,:deal_types
  def index
    params[:page] ||= 1
    params[:rows] ||= 20
    @deals = Deal.order(sort_column + " " + sort_direction).
                                              paginate(:page => params[:page].to_i, :per_page => params[:rows].to_i)
  end

  def show
    @deal = Deal.find(params[:id])
  end

  def new
    @deal = Deal.new
    form_info
  end

  def create
    @deal = Deal.new(params[:deal])
    if @deal.save
      redirect_to [:admin, :generic, @deal], :notice => "Successfully created deal."
    else
      form_info
      render :new
    end
  end

  def edit
    @deal = Deal.find(params[:id])
    form_info
  end

  def update
    @deal = Deal.find(params[:id])
    if @deal.update_attributes(params[:deal])
      redirect_to [:admin, :generic, @deal], :notice  => "Successfully updated deal."
    else
      form_info
      render :edit
    end
  end

  def destroy
    @deal = Deal.find(params[:id])
    @deal.deleted_at = Time.zone.now
    @deal.save
    redirect_to admin_generic_deals_url, :notice => "Successfully deleted deal."
  end

  private
    def form_info

    end

    def product_types
      @select_product_types     ||= ProductType.all.collect{|pt| [pt.name, pt.id]}
    end

    def deal_types
      @select_deal_types     ||= DealType.all.collect{|pt| [pt.name, pt.id]}
    end

    def sort_column
      Deal.column_names.include?(params[:sort]) ? params[:sort] : "buy_quantity"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/views/admin/generic/deals/_form.html.erb
<%= f.error_messages %>

<fieldset>
  <label>Buy Quantity</label>
  <%= f.number_field :buy_quantity %>

  <label>Get Percentage</label>
  <%= f.number_field :get_percentage %>

  <label>Deal Type</label>
  <%= f.number_field :deal_type_id %>

  <label>Product Type</label>
  <%= f.number_field :product_type_id %>

  <label>Get Amount</label>
  <%= f.number_field :get_amount %>

  <label>Deleted at</label>
  <div class='date-select'>
    <%= f.datetime_select :deleted_at %>
  </div>
</fieldset>

app/views/admin/generic/deals/edit.html.erb
<h3>Edit Deal</h3>

<%= form_for @deal, :url => [:admin, :generic, @deal] do |f| %>
  <%=  render :partial => 'form', :locals => {:f => f} %>
  <div class="actions"><%= f.submit 'Update' , :class => 'button' %></div>
<% end %>

<p>
  <%= link_to "Show", [:admin, :generic, @deal], :class => 'button' %> |
  <%= link_to "View All", admin_generic_deals_path, :class => 'button' %>
</p>

app/views/admin/generic/deals/index.html.erb
<div class="admin_title_header clearfix">
  <h3>Deals</h3>
  <%= link_to "New Deal", new_admin_generic_deal_path, :class => "button" %>
</div>

<div class="admin_deals">
  <table>
    <thead>
    <tr class='odd'>
      <th  class='column1_header'><%= sortable 'buy_quantity', 'Buy Quantity' %></th>
      <th>Get Percentage</th>
      <th>Deal Type</th>
      <th>Product Type</th>
      <th>Get Amount</th>
      <th>Deleted At</th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% for deal in @deals %>
      <tr  class='<%= cycle("odd", "")%>'>

          <td><%= link_to deal.buy_quantity, [:admin, :generic, deal] %></td>
          <td><%= deal.get_percentage %></td>
          <td><%= deal.deal_type.name %></td>
          <td><%= deal.product_type.name %></td>
          <td><%= deal.get_amount %></td>
          <td><%= deal.deleted_at %></td>
        <td>
        <%#  YOU SHOULD NOT EDIT THIS..  OLD ORDERS WILL NO LONGER CALCULATE CORRECTLY.  set Deleted_at and create a new promotion %>
        <%#= link_to "", edit_admin_generic_deal_path(deal), :class => 'ss_sprite ss_application_edit' %></td>
        <td><%= link_to "", [:admin, :generic, deal], :data => {:confirm => 'Are you sure?'}, :method => :delete, :class => 'ss_sprite ss_cross' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%= will_paginate @deals %>

app/views/admin/generic/deals/new.html.erb
<h3>New Deal</h3>

<%= form_for @deal, :url => admin_generic_deals_path(@deal) do |f| %>
  <%=  render :partial => 'form', :locals => {:f => f} %>
  <div class="actions"><%= f.submit 'Create' , :class => "button" %></div>
<% end %>

<p><%= link_to "Back to List", admin_generic_deals_path, :class => "button" %></p>

app/views/admin/generic/deals/show.html.erb
<h3>Deal</h3>

<ul>
  <li>
    <label>Buy Quantity:</label>
    <%= @deal.buy_quantity %>
  </li>
  <li>
    <label>Get Percentage:</label>
    <%= @deal.get_percentage %>
  </li>
  <li>
    <label>Deal Type:</label>
    <%= @deal.deal_type.name %>
  </li>
  <li>
    <label>Product Type:</label>
    <%= @deal.product_type.name %>
  </li>
  <li>
    <label>Get Amount:</label>
    <%= @deal.get_amount %>
  </li>
  <li>
    <label>Deleted At:</label>
    <%= @deal.deleted_at %>
  </li>
</ul>
<p>
  <%#  YOU SHOULD NOT EDIT THIS..  OLD ORDERS WILL NO LONGER CALCULATE CORRECTLY.  set Deleted_at and create a new promotion %>
  <%#= link_to "Edit", edit_admin_generic_deal_path(@deal), :class => 'button' %> |
  <%= link_to "Destroy", [:admin, :generic, @deal], :data => {:confirm => 'Are you sure?'}, :method => :delete, :class => 'button' %> |
  <%= link_to "View All", admin_generic_deals_path, :class => 'button' %>
</p>