config/routes.rb
Hadean::Application.routes.draw do

  get "contacts/index"

  resources :user_sessions, :only => [:new, :create, :destroy]

  match 'admin'   => 'admin/overviews#index'
  match 'login'   => 'user_sessions#new'
  match 'logout'  => 'user_sessions#destroy'
  match 'signup'  => 'customer/registrations#new'
  match 'admin/merchandise' => 'admin/merchandise/summary#index'

  get 'about', to: 'statics#about'
  get 'privacy', to: 'statics#privacy'
  get 'terms', to: 'statics#terms'
  get 'contact', to: 'statics#contact'
  post 'send_inquiry', to: 'statics#send_inquiry'

  match 'browse' => 'products#index', as: 'browse'
  match 'category/:product_type_id' => 'products#index', as: 'browse_category'
  match 'color/:property_values_id' => 'products#index', as: 'browse_color'
  match 'price/:price_from' => 'products#index', as: 'browse_price_from'
  match 'price/:price_from/:price_to' => 'products#index', as: 'browse_price_from_to'
  match 'search' => 'products#index', as: 'search'
  match 'search/:search_term' => 'products#index', as: 'search_term'
  
  match 'hallists/search' => 'hallists#index', as: 'hallists_search'
  match 'hallists/search/:search_term' => 'hallists#index', as: 'hallists_search_term'
  
  match 'artists/search' => 'artists#index', as: 'artists_search'
  match 'artists/search/:search_term' => 'artists#index', as: 'artists_search_term'

  match 'contacts/newsletter' => 'contacts#newsletter', as: 'newsletter'
  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'

  match 'collections/delete_collection/:id' => 'collections#delete_collection', as: 'delete_collection'

  resources :comments
  resources :bids, only: [:create]
  
  resources :products, :only => [:index, :show, :create] do
    resources :collection_cart_items, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy], controller: 'products/likes'
  end

  resources :artists, only: [:index] do
    resource :follows, only: [:create, :destroy]
  end

  resources :collections,  :only => [:destroy, :create, :update, :show]
  resources :hallists,  :only => [:index, :destroy, :create, :update, :show]
  resources :states,      :only => [:index]
  resource :about,        :only => [:show]

  root :to => "products#index"

  namespace :customer do
    resources :registrations,   :only => [:new, :create]
    resource  :password_reset,  :only => [:new, :create, :edit, :update]
    resource  :activation,      :only => [:show]
  end

  namespace :myaccount do
    resources :orders, :only => [:index, :show]
    resources :addresses
    resources :credit_cards
    resource  :store_credit, :only => [:show]
    resource  :overview, :only => [:show, :edit, :update]
  end

  namespace :artwork do
    resource :dashboard, only: :show, controller: 'dashboard'
    resources :products do
      resources :variants, only: :destroy
    end
  end

  namespace :shopping do
    resource :paypal_checkout, controller: :paypal_checkout do
      member do
        get :review
      end
    end

    resource :creditcard_checkout, controller: :creditcard_checkout do
      member do
        post :pay
      end
    end

    resources  :cart_items do
      member do
        put :move_to
      end
    end
    resource  :coupon, :only => [:show, :create]
    resources  :orders do
      member do
        get :checkout
      end
    end
    resource :checkout, controller: :checkout, only: [:show, :update] do
      member do
        post :twocheckout_return
      end
    end
    resources  :shipping_methods
    resources  :addresses do
      member do
        put :select_address
      end
    end

  end

  namespace :admin do
    resources :users
    resources :overviews, :only => [:index]

    match "help" => "help#index"

    namespace :rma do
      resources  :orders do
        resources  :return_authorizations do
          member do
            put :complete
          end
        end
      end
      #resources  :shipments
    end

    namespace :history do
      resources  :orders, :only => [:index, :show] do
        resources  :addresses, :only => [:index, :show, :edit, :update, :new, :create]
      end
    end

    namespace :fulfillment do
      resources  :orders do
        member do
          put :create_shipment
        end
        resources  :comments
      end
      resources  :shipments do
        member do
          put :ship
        end
        resources  :addresses , :only => [:edit, :update]# This is for editing the shipment address
      end
    end
    namespace :shopping do
      resources :carts
      resources :products
      resources :users
      namespace :checkout do
        resources :billing_addresses, :only => [:index, :update, :new, :create, :select_address] do
          member do
            put :select_address
          end
        end
        resources :credit_cards
        resource  :order, :only => [:show, :update, :start_checkout_process] do
          member do
            post :start_checkout_process
          end
        end
        resources :shipping_addresses, :only => [:index, :update, :new, :create, :select_address] do
          member do
            put :select_address
          end
        end
        resources :shipping_methods, :only => [:index, :update]
      end
    end
    namespace :config do
      resources :accounts
      resources :overviews
      resources :shipping_categories
      resources :shipping_rates
      resources :shipping_methods
      resources :shipping_zones
      resources :tax_rates
      resources :tax_categories
      resources :messages
    end

    namespace :generic do
      resources :coupons
      resources :deals
    end
    namespace :inventory do
      resources :suppliers
      resources :overviews
      resources :purchase_orders
      resources :receivings
      resources :adjustments
    end

    namespace :merchandise do
      namespace :images do
        resources :products
      end
      resources :properties
      resources :prototypes
      resources :brands
      resources :product_types
      resources :prototype_properties

      namespace :changes do
        resources :products do
          resource :property,          :only => [:edit, :update]
        end
      end

      namespace :wizards do
        resources :brands,              :only => [:index, :create, :update]
        resources :products,            :only => [:new, :create]
        resources :properties,          :only => [:index, :create, :update]
        resources :prototypes,          :only => [:update]
        resources :tax_categories,        :only => [:index, :create, :update]
        resources :shipping_categories, :only => [:index, :create, :update]
        resources :product_types,       :only => [:index, :create, :update]
      end

      namespace :multi do
        resources :products do
          resource :variant,      :only => [:edit, :update]
        end
      end
      resources :products do
        member do
          get :add_properties
          put :activate
          get :featured
        end
        resources :variants
      end
      namespace :products do
        resources :descriptions, :only => [:edit, :update]
      end
    end
    namespace :document do
      resources :invoices
    end
  end

  match '/subregion_options', to: 'application#subregion_options'
  match '/artworks/:id', :to => 'products#show', :as => 'artwork'

  match '/myprofile', :to => 'profile#show', :as => 'myprofile'
  match '/profile/:profile_id/products', :to => 'profiles/products#index', :as => 'profile_products'
  match '/profile/:profile_id/collections', :to => 'profiles/collections#index', :as => 'profile_collections'
  match '/profile/:id', :to => 'profile#show', :as => 'profile'
  match '/:username', :to => 'profile#show', :as => 'personal_urls'
  post '/webhooks/receptor'
end

app/controllers/admin/fulfillment/orders_controller.rb
class Admin::Fulfillment::OrdersController < Admin::Fulfillment::BaseController
  helper_method :sort_column, :sort_direction
  # GET /admin/fulfillment/orders
  def index
    params[:page] ||= 1
    @orders = Order.fulfillment_grid(params).order(sort_column + " " + sort_direction).
                                            paginate(:per_page => 25, :page => params[:page].to_i)

  end

  # GET /admin/fulfillment/orders/1
  def show
    @order = Order.includes([:shipments, {:order_items => [:shipment, :variant]}]).find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @order }
    end
  end

  # GET /admin/fulfillment/orders/1/edit
  def edit
    @order = Order.includes([:shipments, {:order_items => [:shipment, :variant]}]).find(params[:id])
  end


  def create_shipment
    @order = Order.find_by_id(params[:id])
    if @order
      Shipment.create_shipments_with_items(@order)
      @order.reload
    end
  end

  # PUT /admin/fulfillment/orders/1
  def update
    @order    = Order.find_by_id(params[:id])
    @invoice  = @order.invoices.find(params[:invoice_id])

    payment = @order.capture_invoice(@invoice)

##  several things happen on this request
# => Payment is captured
# => Invoice is updated to log leger transactions
# => Shipment is marked as ready to send and associated to the order_items
# => If everything works send the user to the shipment page


## TODO
# => Allow partial payments
# => mark only order_items that will be shipped

    respond_to do |format|
      if payment && payment.success?
        format.html { render :partial => 'success_message' }
      else
        format.html { render :partial => 'failure_message' }
      end
    end
  end

  # DELETE /admin/fulfillment/shipments/1
  # DELETE /admin/fulfillment/shipments/1.xml
  def destroy

    @order    = Order.find(params[:id])
    @invoice  = @order.invoices.find(params[:invoice_id])

    @order.cancel_unshipped_order(@invoice)
    respond_to do |format|
      format.html { render :partial => 'invoice_details', :locals => {:invoice => @invoice} }
      format.json { render :json => @order.to_json }
    end
  end

  protected

  def sort_column
    Order.column_names.include?(params[:sort]) ? params[:sort] : "number"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/admin/history/orders_controller.rb
class Admin::History::OrdersController < Admin::BaseController
  # GET /admin/history/orders
  # GET /admin/history/orders.xml
  def index
    @orders = Order.find_finished_order_grid(params)
  end

  # GET /admin/history/orders/1
  # GET /admin/history/orders/1.xml
  def show
    @order = Order.includes([:ship_address, :invoices,
                             {:shipments => :shipping_method},
                             {:order_items => [
                                                {:variant => [:product, :variant_properties]}]
                              }]).find_by_number(params[:id])
  end

end

app/controllers/admin/shopping/base_controller.rb
#The philosophy of the admin cart is 2-fold.
#
# First these people have admin privileges.  So lets not add security features that they are allowed to use anyway.
#
# Second, the number of people in the Admin Section will not be in the millions.
# => So lets use the mem_cache session store to store more information than we would normal.
# => This will hit the DB much less and should have better performance.

class Admin::Shopping::BaseController < Admin::BaseController
  helper_method :session_admin_cart, :reset_admin_cart#, :new_admin_cart#

  layout 'admin_cart'

  private

  def reset_admin_cart
    session[:admin_cart_id] = new_admin_cart.id
  end

  def session_admin_cart
    if session[:admin_cart_id]
      @admin_cart ||= Cart.find_by_id(session[:admin_cart_id])
      @admin_cart ||= new_admin_cart # just in case the session has a bad ID (normally in development while having 2 apps)
    else
      new_admin_cart
    end
  end

  def new_admin_cart
    @admin_cart = Cart.create(:user => current_user)
    session[:admin_cart_id] = @admin_cart.id
    @admin_cart
  end

  def next_admin_cart_form()
     # if cart is empty
    if !session_admin_cart.customer_id
      return admin_shopping_users_url
    elsif !session_admin_cart.shopping_cart_items
      return admin_shopping_products_url()
    #elsif session_admin_cart[:shipping_address].nil?
    #  return admin_shopping_shipping_addresses_url
    #elsif session_admin_cart[:billing_address].nil?
    #  return admin_shopping_billing_addresses_url()
    #elsif session_admin_cart[:shipping_rate].nil?
    #  return admin_shopping_shipping_methods_url()
    else
      return admin_shopping_products_url()
    #  return nil#admin_shopping_carts_url()
#    elsif session_admin_cart[:coupon].nil?
#      return admin_shopping_coupons_url()
    end
  end

end

app/controllers/admin/shopping/carts_controller.rb
class Admin::Shopping::CartsController < Admin::Shopping::BaseController
  # GET /admin/order/carts
  # GET /admin/order/carts.xml
  def index
    authorize! :create_orders, current_user
    if f = next_admin_cart_form
      redirect_to f
    else
      @cart = session_admin_cart
      @credit_card ||= ActiveMerchant::Billing::CreditCard.new()
      respond_to do |format|
        format.html # index.html.erb
      end
    end
  end

  # GET /admin/order/carts/1
  # GET /admin/order/carts/1.xml
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /admin/order/carts/new
  # GET /admin/order/carts/new.xml
  def new
    @admin_shopping_cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end


  # POST /admin/order/carts
  # POST /admin/order/carts.xml
  def create
    @cart         =  session_admin_cart
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(cc_params)

    if @credit_card.valid?
      #ActiveRecord::Base.transaction do
        @order = Order.new_admin_cart(@cart, {:ip_address => request.remote_ip})
        response = @order.create_invoice( @credit_card,
                                          @order.credited_total,
                                          { :email            => @order.email,
                                            :billing_address  => @cart[:billing_address],
                                            :ip               => request.remote_ip },
                                          @order.amount_to_credit) if @order
      #end

      if @order && response
        if response.success?
          #clear the items out of the session_cart
          @order.remove_user_store_credits
          reset_admin_cart
          ## Render the summary with a success message
          flash[:error] = "Processed order successfully."
          render :action => "success"
        else
          render :action => "failure"
        end
      else
        flash[:error] = "Could not process the Credit Card."
        render :action => 'index' #admin_shopping_carts_url
      end
    else
      flash[:error] = "Credit Card is not valid."
      render :action => 'index'
    end

  end

  # PUT /admin/order/carts/1
  # PUT /admin/order/carts/1.xml
  def update
    @admin_shopping_cart = Cart.find(params[:id])

    respond_to do |format|
      if @admin_shopping_cart.update_attributes(params[:admin_shopping_cart])
        format.html { redirect_to(@admin_shopping_cart, :notice => 'Cart was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /admin/order/carts/1
  # DELETE /admin/order/carts/1.xml
  def destroy
    session_admin_cart = nil

    respond_to do |format|
      format.html { redirect_to(admin_shopping_carts_url) }
    end
  end


  private

  def cc_params
    {
          :type               => params[:type],
          :number             => params[:number],
          :verification_value => params[:verification_value],
          :month              => params[:month],
          :year               => params[:year],
          :first_name         => params[:first_name],
          :last_name          => params[:last_name]
    }
  end
end

app/controllers/admin/shopping/credit_cards_controller.rb
class Admin::Shopping::CreditCardsController < Admin::Shopping::BaseController
  # GET /admin/order/credit_cards
  # GET /admin/order/credit_cards.xml
  def index
    @credit_cards = session_admin_cart[:user].credit_cards.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /admin/order/credit_cards/1
  # GET /admin/order/credit_cards/1.xml
  def show
    @credit_card = session_admin_cart[:user].credit_cards.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /admin/order/credit_cards/new
  # GET /admin/order/credit_cards/new.xml
  def new
    @credit_card = CreditCard.new(:user_id => session_admin_cart[:user].id)

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # POST /admin/order/credit_cards
  # POST /admin/order/credit_cards.xml
  def create
    @credit_card = session_admin_cart[:user].credit_cards.new(params[:credit_card])

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to(@credit_card, :notice => 'Credit card was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end


end

app/controllers/myaccount/orders_controller.rb
class Myaccount::OrdersController < Myaccount::BaseController
  # GET /myaccount/orders
  # GET /myaccount/orders.xml
  def index
    @orders = current_user.finished_orders.find_myaccount_details
  end

  # GET /myaccount/orders/1
  # GET /myaccount/orders/1.xml
  def show
    @order = current_user.finished_orders.includes([:invoices]).find_by_number(params[:id])
  end
  private

  def selected_myaccount_tab(tab)
    tab == 'orders'
  end
end

app/views/shopping/orders/_order_item.html.erb
<div class='span-14 <%= cycle("line_item_blue", "line_item_light_gray") -%>'>
    <div class='span-8 '>
      <%= image_tag(items.first.variant.product.featured_image(:mini)) %>
      <%= items.first.variant.product.name %> Quantity: <%= items.size %>
    </div>
    <div class='span-5  last' style='text-align:left;'>
      <%= raw items.first.variant.display_property_details %>
    </div>
</div>

app/views/shopping/orders/index.html.erb
<% content_for :head do -%>
  <%= stylesheet_link_tag 'tables.css' %>
<% end %>
<div id='order-wrapper' class='span-24'>
  <div class='span-14'>
    <h1>Order Summary</h1>

    <div id='order-items-summary'>
      <% i = 1 %>
      <% @order.order_items.group_by(&:variant_id).each do |variant_id, items| %>
        <div id='order-item-<%= i %>'>
          <%= render :partial => 'order_item', :locals => {:items => items } %>
        </div>
        <% i += 1 %>
      <% end %>
    </div>

    <div id='final-order-shipping-address' class='box span-6 rounded-10' style='text-align:left;'>
      <h5>Shipping Address</h5>
      <%= render :partial => '/shared/compact_address', :locals => {:shopping_address => @order.ship_address} %>
      <%= link_to 'Change address', shopping_addresses_path, :class => 'button green' %>
    </div>
    <div id='final-order-shipping-address' class='box span-6 rounded-8 last' style='text-align:left;'>
      <h5>Billing Address</h5>
      <%= render :partial => '/shared/compact_address', :locals => {:shopping_address => @order.bill_address} %>
    </div>
  </div>
  <div class='pretty_table span-10 last'>
    <table>
      <thead>
        <tr class='odd'>
          <th class='column1_header'>
            Item <span class='ss_sprite ss_application_cascade'></span>

          </th><th>Price:</th><th>Price + Tax</th>
        </tr>
      </thead>
      <% @order.order_items.each do |item| %>
        <tr class='<%= cycle("odd", "")%> '>
          <td><%= item.variant.product.name %></td><td><%= number_to_currency item.price %></td><td><%= number_to_currency item.total %></td>
        </tr>
      <% end %>
      <tr class='odd'>
        <td></td><td>Sub-total:</td><td><%= number_to_currency @order.sub_total %></td>
      </tr>
      <tr>
        <td></td><td>Shipping Charges:</td><td><%= number_to_currency @order.shipping_charges %></td>
      </tr>
      <% if @order.coupon_amount > 0.0 %>
        <tr>
          <td></td><td>Coupon:</td><td><%= number_to_currency @order.coupon_amount %></td>
        </tr>
      <% end %>
      <% if @order.deal_amount && @order.deal_amount > 0.0 %>
        <tr>
          <td></td><td>Promotion:</td><td><%= number_to_currency @order.deal_amount %></td><td></td>
        </tr>
      <% end %>
      <tfoot>
        <tr class='even'>
          <td></td><td>Total:</td><td><em><%= number_to_currency @order.total %></em></td>
        </tr>
      </tfoot>
    </table>
    <div>
  </div>
    <%= form_tag( shopping_order_path(@order),
                                  :method => :put,
                                  #:as   => :order,
                                  :id   => 'purchase_order') do  %>


      <%# text_field(object_name, method, options = {}) %>



      <div class="field column">
        <%= label_tag  :name %>
      </div>
<div class='clear'></div>
      <div class="field column">
        <%= label_tag 'First' %>
         <%= text_field_tag(:first_name, @credit_card.first_name ,:class => 'span-3') %>
      </div>

      <div class="field column">
        <%= label_tag :last_name, 'Last' %>
         <%= text_field_tag(:last_name, @credit_card.last_name,:class => 'span-3') %>
      </div>

      <div class='clear'></div>
      <div class="field column float-left clear-fix">
        <%= label_tag 'Number'%>
         <%= text_field_tag(:number, @credit_card.number ,:class => 'span-4 disableAutoComplete', :autocomplete => "off") %>
      </div>

      <div class="field column float-left">
        <%= label_tag :verification_value, 'VCC'%>
         <%= text_field_tag(:verification_value, @credit_card.verification_value ,:class => 'span-1 disableAutoComplete', :autocomplete => "off") %>
      </div>

      <div class='clear'></div>
      <div class="field column float-left ">
        <%= label_tag :type, 'Type'%>
         <%= select_tag(:type, options_for_select(['visa', 'mastercard'])) %>
      </div>

      <div class="field column float-left">
        <%= label_tag :month %>
        <%= select_tag(:month, options_for_select(['01', '02',  '03', '04', '05', '06', '07', '08', '09', '10', '11', '12' ])) %>
      </div>

      <div class="field column float-left">
        <%= label_tag :year %>
         <%= select_tag(:year, options_for_select((Time.zone.now.year..(Time.zone.now.year + 10)))) %>
      </div>
      <div class='clear'></div>


      <%= submit_tag 'Complete Order', :class => 'button light' %>
    <% end %>
  </div>
</div>