config/routes.rb
Hadean::Application.routes.draw do

  get "contacts/index"

  resources :user_sessions, :only => [:new, :create, :destroy]

  match 'admin'   => 'admin/overviews#index'
  match 'login'   => 'user_sessions#new'
  match 'logout'  => 'user_sessions#destroy'
  match 'signup'  => 'customer/registrations#new'
  match 'admin/merchandise' => 'admin/merchandise/summary#index'

  get 'about', to: 'statics#about'
  get 'privacy', to: 'statics#privacy'
  get 'terms', to: 'statics#terms'
  get 'contact', to: 'statics#contact'
  post 'send_inquiry', to: 'statics#send_inquiry'

  match 'browse' => 'products#index', as: 'browse'
  match 'category/:product_type_id' => 'products#index', as: 'browse_category'
  match 'color/:property_values_id' => 'products#index', as: 'browse_color'
  match 'price/:price_from' => 'products#index', as: 'browse_price_from'
  match 'price/:price_from/:price_to' => 'products#index', as: 'browse_price_from_to'
  match 'search' => 'products#index', as: 'search'
  match 'search/:search_term' => 'products#index', as: 'search_term'
  
  match 'hallists/search' => 'hallists#index', as: 'hallists_search'
  match 'hallists/search/:search_term' => 'hallists#index', as: 'hallists_search_term'
  
  match 'artists/search' => 'artists#index', as: 'artists_search'
  match 'artists/search/:search_term' => 'artists#index', as: 'artists_search_term'

  match 'contacts/newsletter' => 'contacts#newsletter', as: 'newsletter'
  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'

  match 'collections/delete_collection/:id' => 'collections#delete_collection', as: 'delete_collection'

  resources :comments
  resources :bids, only: [:create]
  
  resources :products, :only => [:index, :show, :create] do
    resources :collection_cart_items, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy], controller: 'products/likes'
  end

  resources :artists, only: [:index] do
    resource :follows, only: [:create, :destroy]
  end

  resources :collections,  :only => [:destroy, :create, :update, :show]
  resources :hallists,  :only => [:index, :destroy, :create, :update, :show]
  resources :states,      :only => [:index]
  resource :about,        :only => [:show]

  root :to => "products#index"

  namespace :customer do
    resources :registrations,   :only => [:new, :create]
    resource  :password_reset,  :only => [:new, :create, :edit, :update]
    resource  :activation,      :only => [:show]
  end

  namespace :myaccount do
    resources :orders, :only => [:index, :show]
    resources :addresses
    resources :credit_cards
    resource  :store_credit, :only => [:show]
    resource  :overview, :only => [:show, :edit, :update]
  end

  namespace :artwork do
    resource :dashboard, only: :show, controller: 'dashboard'
    resources :products do
      resources :variants, only: :destroy
    end
  end

  namespace :shopping do
    resource :paypal_checkout, controller: :paypal_checkout do
      member do
        get :review
      end
    end

    resource :creditcard_checkout, controller: :creditcard_checkout do
      member do
        post :pay
      end
    end

    resources  :cart_items do
      member do
        put :move_to
      end
    end
    resource  :coupon, :only => [:show, :create]
    resources  :orders do
      member do
        get :checkout
      end
    end
    resource :checkout, controller: :checkout, only: [:show, :update] do
      member do
        post :twocheckout_return
      end
    end
    resources  :shipping_methods
    resources  :addresses do
      member do
        put :select_address
      end
    end

  end

  namespace :admin do
    resources :users
    resources :overviews, :only => [:index]

    match "help" => "help#index"

    namespace :rma do
      resources  :orders do
        resources  :return_authorizations do
          member do
            put :complete
          end
        end
      end
      #resources  :shipments
    end

    namespace :history do
      resources  :orders, :only => [:index, :show] do
        resources  :addresses, :only => [:index, :show, :edit, :update, :new, :create]
      end
    end

    namespace :fulfillment do
      resources  :orders do
        member do
          put :create_shipment
        end
        resources  :comments
      end
      resources  :shipments do
        member do
          put :ship
        end
        resources  :addresses , :only => [:edit, :update]# This is for editing the shipment address
      end
    end
    namespace :shopping do
      resources :carts
      resources :products
      resources :users
      namespace :checkout do
        resources :billing_addresses, :only => [:index, :update, :new, :create, :select_address] do
          member do
            put :select_address
          end
        end
        resources :credit_cards
        resource  :order, :only => [:show, :update, :start_checkout_process] do
          member do
            post :start_checkout_process
          end
        end
        resources :shipping_addresses, :only => [:index, :update, :new, :create, :select_address] do
          member do
            put :select_address
          end
        end
        resources :shipping_methods, :only => [:index, :update]
      end
    end
    namespace :config do
      resources :accounts
      resources :overviews
      resources :shipping_categories
      resources :shipping_rates
      resources :shipping_methods
      resources :shipping_zones
      resources :tax_rates
      resources :tax_categories
      resources :messages
    end

    namespace :generic do
      resources :coupons
      resources :deals
    end
    namespace :inventory do
      resources :suppliers
      resources :overviews
      resources :purchase_orders
      resources :receivings
      resources :adjustments
    end

    namespace :merchandise do
      namespace :images do
        resources :products
      end
      resources :properties
      resources :prototypes
      resources :brands
      resources :product_types
      resources :prototype_properties

      namespace :changes do
        resources :products do
          resource :property,          :only => [:edit, :update]
        end
      end

      namespace :wizards do
        resources :brands,              :only => [:index, :create, :update]
        resources :products,            :only => [:new, :create]
        resources :properties,          :only => [:index, :create, :update]
        resources :prototypes,          :only => [:update]
        resources :tax_categories,        :only => [:index, :create, :update]
        resources :shipping_categories, :only => [:index, :create, :update]
        resources :product_types,       :only => [:index, :create, :update]
      end

      namespace :multi do
        resources :products do
          resource :variant,      :only => [:edit, :update]
        end
      end
      resources :products do
        member do
          get :add_properties
          put :activate
          get :featured
        end
        resources :variants
      end
      namespace :products do
        resources :descriptions, :only => [:edit, :update]
      end
    end
    namespace :document do
      resources :invoices
    end
  end

  match '/subregion_options', to: 'application#subregion_options'
  match '/artworks/:id', :to => 'products#show', :as => 'artwork'

  match '/myprofile', :to => 'profile#show', :as => 'myprofile'
  match '/profile/:profile_id/products', :to => 'profiles/products#index', :as => 'profile_products'
  match '/profile/:profile_id/collections', :to => 'profiles/collections#index', :as => 'profile_collections'
  match '/profile/:id', :to => 'profile#show', :as => 'profile'
  match '/:username', :to => 'profile#show', :as => 'personal_urls'
  post '/webhooks/receptor'
end

app/controllers/admin/shopping/base_controller.rb
#The philosophy of the admin cart is 2-fold.
#
# First these people have admin privileges.  So lets not add security features that they are allowed to use anyway.
#
# Second, the number of people in the Admin Section will not be in the millions.
# => So lets use the mem_cache session store to store more information than we would normal.
# => This will hit the DB much less and should have better performance.

class Admin::Shopping::BaseController < Admin::BaseController
  helper_method :session_admin_cart, :reset_admin_cart#, :new_admin_cart#

  layout 'admin_cart'

  private

  def reset_admin_cart
    session[:admin_cart_id] = new_admin_cart.id
  end

  def session_admin_cart
    if session[:admin_cart_id]
      @admin_cart ||= Cart.find_by_id(session[:admin_cart_id])
      @admin_cart ||= new_admin_cart # just in case the session has a bad ID (normally in development while having 2 apps)
    else
      new_admin_cart
    end
  end

  def new_admin_cart
    @admin_cart = Cart.create(:user => current_user)
    session[:admin_cart_id] = @admin_cart.id
    @admin_cart
  end

  def next_admin_cart_form()
     # if cart is empty
    if !session_admin_cart.customer_id
      return admin_shopping_users_url
    elsif !session_admin_cart.shopping_cart_items
      return admin_shopping_products_url()
    #elsif session_admin_cart[:shipping_address].nil?
    #  return admin_shopping_shipping_addresses_url
    #elsif session_admin_cart[:billing_address].nil?
    #  return admin_shopping_billing_addresses_url()
    #elsif session_admin_cart[:shipping_rate].nil?
    #  return admin_shopping_shipping_methods_url()
    else
      return admin_shopping_products_url()
    #  return nil#admin_shopping_carts_url()
#    elsif session_admin_cart[:coupon].nil?
#      return admin_shopping_coupons_url()
    end
  end

end

app/controllers/admin/shopping/carts_controller.rb
class Admin::Shopping::CartsController < Admin::Shopping::BaseController
  # GET /admin/order/carts
  # GET /admin/order/carts.xml
  def index
    authorize! :create_orders, current_user
    if f = next_admin_cart_form
      redirect_to f
    else
      @cart = session_admin_cart
      @credit_card ||= ActiveMerchant::Billing::CreditCard.new()
      respond_to do |format|
        format.html # index.html.erb
      end
    end
  end

  # GET /admin/order/carts/1
  # GET /admin/order/carts/1.xml
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /admin/order/carts/new
  # GET /admin/order/carts/new.xml
  def new
    @admin_shopping_cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end


  # POST /admin/order/carts
  # POST /admin/order/carts.xml
  def create
    @cart         =  session_admin_cart
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(cc_params)

    if @credit_card.valid?
      #ActiveRecord::Base.transaction do
        @order = Order.new_admin_cart(@cart, {:ip_address => request.remote_ip})
        response = @order.create_invoice( @credit_card,
                                          @order.credited_total,
                                          { :email            => @order.email,
                                            :billing_address  => @cart[:billing_address],
                                            :ip               => request.remote_ip },
                                          @order.amount_to_credit) if @order
      #end

      if @order && response
        if response.success?
          #clear the items out of the session_cart
          @order.remove_user_store_credits
          reset_admin_cart
          ## Render the summary with a success message
          flash[:error] = "Processed order successfully."
          render :action => "success"
        else
          render :action => "failure"
        end
      else
        flash[:error] = "Could not process the Credit Card."
        render :action => 'index' #admin_shopping_carts_url
      end
    else
      flash[:error] = "Credit Card is not valid."
      render :action => 'index'
    end

  end

  # PUT /admin/order/carts/1
  # PUT /admin/order/carts/1.xml
  def update
    @admin_shopping_cart = Cart.find(params[:id])

    respond_to do |format|
      if @admin_shopping_cart.update_attributes(params[:admin_shopping_cart])
        format.html { redirect_to(@admin_shopping_cart, :notice => 'Cart was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /admin/order/carts/1
  # DELETE /admin/order/carts/1.xml
  def destroy
    session_admin_cart = nil

    respond_to do |format|
      format.html { redirect_to(admin_shopping_carts_url) }
    end
  end


  private

  def cc_params
    {
          :type               => params[:type],
          :number             => params[:number],
          :verification_value => params[:verification_value],
          :month              => params[:month],
          :year               => params[:year],
          :first_name         => params[:first_name],
          :last_name          => params[:last_name]
    }
  end
end

app/controllers/admin/shopping/checkout/base_controller.rb
class Admin::Shopping::Checkout::BaseController < Admin::Shopping::BaseController
  helper_method :session_admin_order

  private

  def checkout_user
    session_admin_cart.customer
  end

  def next_admin_order_form()
     # if cart is empty
    if !session_admin_cart.customer_id
      return admin_shopping_users_url
    elsif !session_admin_cart.shopping_cart_items
      return admin_shopping_products_url()
    elsif session_admin_order.ship_address_id.nil?
      return admin_shopping_checkout_shipping_addresses_url
    elsif session_admin_order.bill_address_id.nil?
      return admin_shopping_checkout_billing_addresses_url()
    elsif session_admin_order.order_items.any?{|oi| oi.shipping_rate_id.nil?}
      return admin_shopping_checkout_shipping_methods_url()
    else
      return nil #admin_shopping_carts_url()
#    elsif session_admin_cart[:coupon].nil?
#      return admin_shopping_coupons_url()
    end
  end

  def session_admin_order
    find_or_create_order
  end

  def session_order_id
    session[:order_admin_id] ? session[:order_admin_id] : find_or_create_order.id
  end

  def find_or_create_order
    return @session_admin_order if @session_admin_order
    if session[:order_admin_id]
      #puts 'if entra de find or create'
      @session_admin_order = checkout_user.orders.includes([ {:ship_address => :state},
                                                      {:bill_address => :state},
                                                      {:order_items =>
                                                        {:variant =>
                                                          {:product => :images }}}]).find(session[:order_admin_id])
      create_order if !@session_admin_order.in_progress?
    else
      #puts 'else find or create'
      create_order
    end
    @session_admin_order
  end


  def create_order
    @session_admin_order = checkout_user.orders.create(:number       => Time.now.to_i,
                                                :ip_address   => request.env['REMOTE_ADDR'],
                                                :bill_address => checkout_user.billing_address  )
    add_new_cart_items(session_cart.shopping_cart_items)
    session[:order_admin_id] = @session_admin_order.id
  end

  def add_new_cart_items(items)
    items.each do |item|
      @session_admin_order.add_items(item.variant, item.quantity)
    end
  end

  def order_completed!
    session[:admin_cart_id] = nil
    session[:order_admin_id] = nil
  end
end

app/controllers/admin/shopping/checkout/shipping_methods_controller.rb
class Admin::Shopping::Checkout::ShippingMethodsController < Admin::Shopping::Checkout::BaseController

  def index
    unless find_or_create_order.ship_address_id
      flash[:notice] = I18n.t('select_address_before_shipping_method')
      redirect_to admin_shopping_checkout_shipping_addresses_url
    else
      ##  TODO  refactopr this method... it seems a bit lengthy
      @shipping_method_ids = session_admin_order.ship_address.state.shipping_zone.shipping_method_ids
      session_admin_order.find_sub_total
      @order_items = OrderItem.includes({:variant => {:product => :shipping_category}}).order_items_in_cart(session_admin_order.id)
      #session_order.order_
      @order_items.each do |item|
        item.variant.product.available_shipping_rates = ShippingRate.with_these_shipping_methods(item.variant.product.shipping_category.shipping_rate_ids, @shipping_method_ids)
      end

      respond_to do |format|
        format.html # index.html.erb
      end
    end
  end

  def update
    all_selected = true
    params[:shipping_category].each_pair do |category_id, rate_id|#[rate]
      if rate_id
        items = order_items_with_category(category_id)

        OrderItem.update_all("shipping_rate_id = #{rate_id}","id IN (#{items.map{|i| i.id}.join(',')})")
      else
        all_selected = false
      end
    end
    respond_to do |format|
      if all_selected
        format.html { redirect_to(admin_shopping_checkout_order_url, :notice => I18n.t('shipping_method_updated')) }
      else
        format.html { redirect_to( admin_shopping_checkout_shipping_methods_url, :notice => I18n.t('all_shipping_methods_must_be_selected')) }
      end
    end
  end
  private

  def order_items_with_category(category_id)
    items = OrderItem.includes([{:variant => :product}]).
                      where(['order_items.order_id = ? AND
                              products.shipping_category_id = ?', session_order_id, category_id])
  end

  def form_info

  end
end

app/helpers/shopping/checkout_helper.rb
module Shopping::CheckoutHelper
end

app/views/shopping/checkout/_checkout_modal.html.haml
= form_tag(pay_shopping_creditcard_checkout_path,:method => :post, :class => 'span12') do
  = text_field_tag(:name, @credit_card.name , :placeholder => 'NAME IS AT APPEARS ON YOUR CARD*', :class => 'span8')
  %div#error_card_name.buena.span3
    *Escribe un nombre
  = text_field_tag(:number, @credit_card.number , :placeholder => 'CARD NUMBER*', :class => 'span8')
  %div#error_card_number.buena.span3
    *El numero es incorrecto
  = text_field_tag(:verification_value, @credit_card.verification_value , :placeholder => 'CVV*', :class => 'span8')
  %div#error_card_cvc.buena.span3
    *Escribe un cvc correcto
  %br
  = select_tag(:month, options_for_select(['01', '02',  '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']), { :class => 'span4' })

  = select_tag(:year, options_for_select((Time.zone.now.year..(Time.zone.now.year + 10))), { :class => 'span4' })

  = text_field_tag(:address, '', :placeholder => 'ADDRESS*', :class => 'span8')
  %br

  = text_field_tag(:state, '', :placeholder => 'STATE*', :class => 'span4')

  = text_field_tag(:city, '', :placeholder => 'CITY*', :class => 'span4')
  %br

  = country_select_tag 'order[ship_address_attributes][country]', {priority: %w(US CA MX), prompt: 'Please select a country'}, {:class => 'span4'}

  = text_field_tag(:zip, '', :placeholder => 'ZIP*', :class => 'span4')

  = hidden_field_tag(:total, @order.total)
  - products = []
  - @order.order_items.each do |item, index|
    - products.push("#{item.variant.product.id}-#{item.variant.product.name}-#{item.price}")
  = hidden_field_tag(:products, products)

  = submit_tag 'Complete Order' , {:disabled => true, class: 'complete-order pull-right', id: 'complete_order'}

- content_for :javascript do
  var card_name = false,
  card_number = false,
  card_cvc = false;

  $('#name').live('keyup',function(){
  if($(this).val() != ''){
  correct('name');
  card_name = true;
  $('#complete_order')[0].disabled = enable_submit();
  } else{
  error('name');
  card_name = false;
  $('#complete_order')[0].disabled = enable_submit();
  }
  });
  $('#number').live('keyup',function(){
  if(Conekta.card.validateNumber($(this).val())){
  correct('number');
  card_number = true;
  $('#complete_order')[0].disabled = enable_submit();
  } else{
  error('number');
  card_number = false;
  $('#complete_order')[0].disabled = enable_submit();
  }
  });
  $('#verification_value').live('keyup',function(){
  if(Conekta.card.validateCVC($(this).val())){
  correct('cvc');
  card_cvc = true;
  $('#complete_order')[0].disabled = enable_submit();
  } else{
  error('cvc');
  card_cvc = false;
  $('#complete_order')[0].disabled = enable_submit();
  }
  });

  function correct(input){
  $('#error_card_'+input).removeClass('mala');
  $('#error_card_'+input).addClass('buena');
  }

  function error(input){
  $('#error_card_'+input).removeClass('buena');
  $('#error_card_'+input).addClass('mala');
  }

  function enable_submit(){
  if(card_name && card_number && card_cvc){
  return false;
  }else{
  return true;
  }
  }

app/views/shopping/checkout/_form.html.haml
.row-fluid
  #checkout_section.span10
    - @order.order_items.each do |item|
      %fieldset.basic-info
        .row-fluid.span5
          .span4
            = image_tag item.variant.product.decorator().featured_image(:small)
          .span6
            #name-product
              = item.variant.product.name
            #description-product
              = User.find_by_brand_id(item.variant.product.brand_id).first_name

        .span7
          %legend
            %center
              .span3
                1
              .span3
                USD
                = number_to_currency item.price
              .span3
                USD
                = number_to_currency item.price
              .span3
                - user = current_user.present? ? current_user.id : 60
                - cart_item = CartItem.find_by_cart_id_and_user_id_and_active_and_variant_id(session_cart,user,true, item.variant.id)
                - if cart_item.present?
                  = link_to '/shopping/cart_items/'+ cart_item.id.to_s+'?variant_id='+item.variant_id.to_s, class: 'delete-item-checkout', :method => :delete, remote: true do
                    = image_tag('tache.png')
    %br

      %fieldset.basic-info
        .span5
        #total.span7
          %legend
            %center
              .charge-title.span3
                Total:
              .span3
                = select_tag("select_divisa", options_for_select(['USD', 'MXN']), { :class => 'span6 divisas' })
              .span3#total_item
                = number_to_currency @order.total || 0


      %fieldset.social-web-info
        .row-fluid#shipping-address
          = form_tag(pay_shopping_creditcard_checkout_path,:method => :post, :class => 'span12') do
            .row-fluid
              .span6.shipping-border
                %legend 2. SHIPPING ADDRESS
                .social-info.span12
                  %span.help-block
                    *Please fill your shipping address before checkout.
                  = text_field_tag 'ship_address_first_name', @order.ship_address.try(:first_name), placeholder: 'FIRST NAME*', class: 'span7'
                  %br
                  = text_field_tag 'ship_address_last_name', @order.ship_address.try(:last_name), placeholder: 'LAST NAME*', class: 'span7'
                  %br
                  = text_field_tag 'ship_address_address1', @order.ship_address.try(:address1), placeholder: 'STREET ADDRESS*', class: 'span7'
                  %br
                  = text_field_tag 'ship_address_address2', @order.ship_address.try(:address2), placeholder: 'APT/FLR/BLDG', class: 'span7'
                  %br
                  = text_field_tag 'ship_address_city', @order.ship_address.try(:city), placeholder: 'CITY*', class: 'span7'
                  %br
                  = country_select_tag 'ship_address_country', {priority: %w(US CA MX), prompt: 'Please select a country'}, placeholder: 'Select Country', class: 'span7'
                  %br
                  = text_field_tag 'ship_address_zip_code]', @order.ship_address.try(:zip_code), placeholder: 'ZIP CODE*', class: 'span7'

              .span6
                %legend 3. PAYMENT METHOD
                .span4#credit
                  = radio_button_tag :payment_method, 'card', true
                  %span
                  = image_tag 'mastercard.png', :class => 'imagenes-pago'
                  %span
                  %span
                  = image_tag 'visa.png', :class => 'imagenes-pago'
                .span4#oxxo
                  = radio_button_tag :payment_method, 'oxxo'
                  %span
                  = image_tag 'oxxo.png', :class => 'imagenes-pago'
                %br

                .web-info#credit_card_payment
                  = text_field_tag(:name, @credit_card.name , :placeholder => 'NAME AS IT APPEARS ON YOUR CARD*', :class => 'span8')
                  %div#error_card_name.buena.span3
                    * Name is a required field
                  = text_field_tag(:number, @credit_card.number , :placeholder => 'CARD NUMBER*', :class => 'span8')
                  %div#error_card_number.buena.span3
                    * Card number is incorrect
                  = text_field_tag(:verification_value, @credit_card.verification_value , :placeholder => 'CVV*', :class => 'span8')
                  %div#error_card_cvc.buena.span3
                    * CVV is incorrect
                  %br
                  = select_tag(:month, options_for_select(['01', '02',  '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']), { :class => 'span4' })

                  = select_tag(:year, options_for_select((Time.zone.now.year..(Time.zone.now.year + 10))), { :class => 'span4' })

                  = text_field_tag(:address_credit, '', :placeholder => 'ADDRESS*', :class => 'span8')
                  %br

                  = text_field_tag(:state, '', :placeholder => 'STATE*', :class => 'span4')

                  = text_field_tag(:city, '', :placeholder => 'CITY*', :class => 'span4')
                  %br

                  //= country_select_tag 'order[ship_address_attributes][country]', {priority: %w(US CA MX), prompt: 'Please select a country'}, {:class => 'span4'}
                  = text_field_tag(:country, '', :placeholder => 'COUNTRY*', :class => 'span4')

                  = text_field_tag(:zip, '', :placeholder => 'ZIP*', :class => 'span4')

                  = hidden_field_tag(:total, @order.total)
                  = hidden_field_tag(:currency, 'USD')
                  - products = []
                  - @order.order_items.each do |item, index|
                    - products.push("#{item.variant.product.id}-#{item.variant.product.name} ,")
                  = hidden_field_tag(:products, products)
                  %br

                  %span#siteseal
                    %script{type: 'text/javascript', src:'https://seal.godaddy.com/getSeal?sealID=hFpmKOe1nFTz1D0JePmpnEpKMe7tLZrKKTTO075feiBPI2prRql'}

                  = submit_tag '' , {:disabled => true, class: 'complete-order', id: 'complete_order'}

                .web-info#oxxo_payment
                  = hidden_field_tag(:total, @order.total)
                  = hidden_field_tag(:currency, 'USD')
                  - products = []
                  - @order.order_items.each do |item, index|
                    - products.push("#{item.variant.product.id}-#{item.variant.product.name}")
                  = hidden_field_tag(:products, products)
                  %br
                  %br
                  * YOU WILL RECEIVE AN ORDER CONFIRMATION ONCE YOU COMPLETE THE PROCESS. THEN YOU SHOULD USE THIS INFORMATION TO PAY AT YOUR NEAREST OXXO.
                  %br
                  %br
                  = submit_tag '' , {class: 'complete-order', id: 'complete_oxxo'}

- content_for :javascript do
  var card_name = false,
  card_number = false,
  card_cvc = false;

  $('#name').live('keyup',function(){
  if($(this).val() != ''){
  correct('name');
  card_name = true;
  $('#complete_order')[0].disabled = enable_submit();
  } else{
  error('name');
  card_name = false;
  $('#complete_order')[0].disabled = enable_submit();
  }
  });
  $('#number').live('keyup',function(){
  if(Conekta.card.validateNumber($(this).val())){
  correct('number');
  card_number = true;
  $('#complete_order')[0].disabled = enable_submit();
  } else{
  error('number');
  card_number = false;
  $('#complete_order')[0].disabled = enable_submit();
  }
  });
  $('#verification_value').live('keyup',function(){
  if(Conekta.card.validateCVC($(this).val())){
  correct('cvc');
  card_cvc = true;
  $('#complete_order')[0].disabled = enable_submit();
  } else{
  error('cvc');
  card_cvc = false;
  $('#complete_order')[0].disabled = enable_submit();
  }
  });

  $('#oxxo').live('change',function(){
  $('#credit_card_payment').removeClass('mala');
  $('#credit_card_payment').addClass('buena');
  $('#oxxo_payment').removeClass('buena');
  $('#oxxo_payment').addClass('mala');
  });

  $('#credit').live('change',function(){
  $('#oxxo_payment').removeClass('mala');
  $('#credit_card_payment').addClass('mala');
  });

  function correct(input){
  $('#error_card_'+input).removeClass('mala');
  $('#error_card_'+input).addClass('buena');
  }

  function error(input){
  $('#error_card_'+input).removeClass('buena');
  $('#error_card_'+input).addClass('mala');
  }

  function enable_submit(){
  if(card_name && card_number && card_cvc){
  return false;
  }else{
  return true;
  }
  }

  $('#select_divisa').live('change',function(){
  var value = $(this).val(), rate, exchange;
  var url = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20yahoo.finance.xchange%20where%20pair%20in%20(%22USD"+value+"%22)&format=json&env=store://datatables.org/alltableswithkeys";
  $.getJSON(url + "&callback=?", null, function(response) {
  rate = response.query.results.rate.Rate;
  exchange = formatCurrency(rate * #{@order.total});
  $('#total_item').text('$'+exchange);
  $('input:hidden[name="total"]').val(exchange);
  $('input:hidden[name="currency"]').val(value);
  });

  function formatCurrency(num) {
  num = isNaN(num) || num === '' || num === null ? 0.00 : num;
  return parseFloat(num).toFixed(2);
  }

  });

app/views/shopping/checkout/show.html.haml
.gray-main-container-checkout
  .row-fluid
    #checkout_section.span10
      .span5
        %legend 1. YOUR ORDER
      .span7
        %legend
          %center
            .span3
              QUANTITY
            .span3
              PRICE
            .span3
              SUBTOTAL
            .span3
              DELETE
  = render :partial => 'form'


- content_for :javascript do
  $(document).ready(function () {
  if(!window.current_user){
  $('#artwork-details-modal').modal('hide');
  Arto.popovers.closeCart();
  $('#login-modal').modal({
  keyboard: false,
  backdrop: 'static'
  });
  $('.login-close-modal').click(function(){
  window.location.href = '/';
  });
  }
  });